import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.premi.st/lfs/Lab Grotesque.css" rel="stylesheet" />
      </head>
      <body>{children}</body>
    </html>
  );
}
